In [81]:
import argparse
import json
import re
import sys
from biom import load_table

control_pattern_default = r"(blank|control|neg|ntc|water|reagent)"
table_path = "../data/V4_stool/V4_stool.biom"
ambiguities_path = "../data/V4_stool/V4_stool.biom.ambiguities"

# Compile control regex
is_control = re.compile(control_pattern_default, re.I).search

# Load table
try:
    table = load_table(table_path)
except Exception as e:
    sys.exit(f"[error] failed to load BIOM table '{table_path}': {e}")

# Load ambiguities mapping
try:
    with open(ambiguities_path) as f:
        ambig = json.load(f)
except Exception as e:
    sys.exit(f"[error] failed to read ambiguities JSON '{ambiguities_path}': {e}")

# Current sample IDs present in table
present = set(table.ids(axis="sample"))

keep = set()
sample_to_idx = {sample_id: i for i, sample_id in enumerate(table.ids(axis="sample"))}
idx_to_sample = {i: sample_id for sample_id, i in sample_to_idx.items()}
sample_depths = table.sum(axis='sample')

# Helper: total observation count (sequencing depth) for a sample
def depth(sample_id: str) -> float:
    # table.sum(axis='sample', ids=[id]) returns a 1-element ndarray
    return float(sample_depths[sample_to_idx[sample_id]])

In [76]:

print(len(present), "samples before filtering")

# for sample_id in present:
#     print(f"sample_id: {sample_id}")
#     print(depth(sample_id))
#     break

42500 samples before filtering

In [ ]:
# import random
# def test_depth(sample_id: str) -> float:
#     return random.randint(1000, 10000)

In [ ]:
# kept items from replicate sets
clip_count = 5000
kept_from_replicates = 0
replicate_total = len([run for runs in ambig.values() for run in runs])

for canon, runs in ambig.items():
    # print(f"canon: {canon}, runs: {runs}")
    
    if is_control(canon):
        print(f"  skipping control run: {canon}")
        continue
    avail = [run for run in runs if run in present]
    if not avail:
        print(f"  no available samples for run: {canon}")
        continue
    best = max(avail, key=depth)
    if depth(best) < clip_count:
        print(f"  skipping low-depth run: {best} (depth: {depth(best)})")
        continue
    # print(best)
    keep.add(best)
    kept_from_replicates += 1
print(f"kept {kept_from_replicates} samples out of {replicate_total} ambiguous samples.")

  skipping low-depth run: 10564.DC6MEYNB.134305 (depth: 3513.0)
  skipping low-depth run: 10564.O9G6DQH2.134305 (depth: 2745.0)
  skipping low-depth run: 10317.X00215889.147023 (depth: 28.0)
  skipping low-depth run: 10317.000001525.131452 (depth: 131.0)
  skipping low-depth run: 10317.X00214414.147023 (depth: 51.0)
  skipping low-depth run: 10564.QCMUUEDW.134305 (depth: 3417.0)
  skipping low-depth run: 2086.1325500812A.131614 (depth: 9.0)
  skipping low-depth run: 2086.1325904517.129439 (depth: 15.0)
  skipping low-depth run: 10317.000020791.131424 (depth: 85.0)
  skipping low-depth run: 10317.000038111.131418 (depth: 4315.0)
  skipping low-depth run: 10317.X00215244.156882 (depth: 80.0)
  skipping low-depth run: 2086.1325401895.129439 (depth: 4.0)
  skipping low-depth run: 10564.74ZDKQVK.134305 (depth: 4977.0)
  skipping low-depth run: 10564.YZL1C941.134305 (depth: 4883.0)
  skipping low-depth run: 10564.8HDXIBAS.134305 (depth: 3127.0)
  skipping low-depth run: 10564.CE3XUVX2.134305 (depth: 4345.0)
  skipping low-depth run: 10564.GXRXGLH3.134305 (depth: 2062.0)
  skipping low-depth run: 2086.1326305912.129439 (depth: 196.0)
  skipping low-depth run: 10317.X00214169.156882 (depth: 70.0)
  skipping low-depth run: 2086.1326305770.131614 (depth: 1665.0)
  skipping low-depth run: 10317.000041950.128247 (depth: 4058.0)
  skipping low-depth run: 10564.QG6Q3VMK.134305 (depth: 4645.0)
  skipping low-depth run: 10317.X00214932.156882 (depth: 785.0)
  skipping low-depth run: 10564.KIZIOL89.134305 (depth: 4404.0)
  skipping low-depth run: 10317.X00215474.156882 (depth: 213.0)
  skipping low-depth run: 10317.X00214732.156882 (depth: 1110.0)
  skipping low-depth run: 10564.97I96IK4.134305 (depth: 2424.0)
  skipping low-depth run: 2086.1325500976A.131614 (depth: 7.0)
  skipping low-depth run: 10317.000023099.129190 (depth: 3349.0)
  skipping low-depth run: 10317.X00215680.156882 (depth: 72.0)
  skipping low-depth run: 10564.9PY3RYTB.134305 (depth: 4301.0)
  skipping low-depth run: 2086.1325307336.129439 (depth: 4.0)
  skipping low-depth run: 2086.1325500852A.129439 (depth: 4.0)
  skipping low-depth run: 10317.X00215648.156882 (depth: 110.0)
  skipping low-depth run: 10317.000012100.127160 (depth: 283.0)
  skipping low-depth run: 2086.1326102104.129439 (depth: 23.0)
  skipping low-depth run: 10317.000040395.128247 (depth: 4175.0)
  skipping low-depth run: 10564.BM9MHXUD.134305 (depth: 4119.0)
  skipping low-depth run: 2086.1325904518.131614 (depth: 3449.0)
  skipping low-depth run: 10564.BKW5E7F4.134305 (depth: 4955.0)
  skipping low-depth run: 2086.1325904513.129439 (depth: 9.0)
  skipping low-depth run: 10317.000006695.129019 (depth: 590.0)
  skipping low-depth run: 2086.1326601620.129439 (depth: 20.0)
  skipping low-depth run: 10564.V6RQXJPE.134305 (depth: 3250.0)
  skipping low-depth run: 10317.X00215588.156882 (depth: 74.0)
  skipping low-depth run: 10317.X00214267.146211 (depth: 48.0)
  skipping low-depth run: 10564.3XAL3UBS.134305 (depth: 3383.0)
  skipping low-depth run: 2086.1325900759.131614 (depth: 8.0)
  skipping low-depth run: 10564.8LK21NXL.134305 (depth: 4279.0)
  skipping low-depth run: 10317.000009400.129728 (depth: 4378.0)
  skipping low-depth run: 10317.000020474.128800 (depth: 34.0)
  skipping low-depth run: 10317.000107736.132545 (depth: 189.0)
  skipping low-depth run: 2086.1325307331.131614 (depth: 4.0)
  skipping low-depth run: 10564.NYYC95BI.134305 (depth: 2678.0)
  skipping low-depth run: 2086.1325900907.129439 (depth: 5.0)
  skipping low-depth run: 10564.XI91FUC4.134305 (depth: 2847.0)
  skipping low-depth run: 2086.1326102116.129439 (depth: 4524.0)
  skipping low-depth run: 10564.TPC4DXSR.134305 (depth: 4464.0)
  skipping low-depth run: 10564.PGFKX87F.134305 (depth: 4054.0)
  skipping low-depth run: 10564.1AIL9FDX.134305 (depth: 2733.0)
  skipping low-depth run: 10317.X00214116.156882 (depth: 63.0)
  skipping low-depth run: 2086.1325904810.129439 (depth: 4.0)
  skipping low-depth run: 10564.42YFD61N.134305 (depth: 3768.0)
  skipping low-depth run: 10564.SFZAU2VG.134305 (depth: 2659.0)
  skipping low-depth run: 10564.DMEOOJFG.134305 (depth: 2442.0)
  skipping low-depth run: 10564.N6YWXQDS.134305 (depth: 3431.0)
  skipping low-depth run: 10317.000032973.132132 (depth: 2181.0)
  skipping low-depth run: 2086.1325904638.129439 (depth: 24.0)
  skipping low-depth run: 2086.1325401984.129439 (depth: 5.0)
  skipping low-depth run: 2086.1326305915.129439 (depth: 260.0)
  skipping low-depth run: 10317.000051246.130783 (depth: 4512.0)
  skipping low-depth run: 2086.1325401896.129439 (depth: 4422.0)
  skipping low-depth run: 10317.000066944.129742 (depth: 510.0)
  skipping low-depth run: 10317.000105630.127418 (depth: 471.0)
  skipping low-depth run: 10564.DJ3SQ1HX.134305 (depth: 4771.0)
  skipping low-depth run: 2086.1325901664.131614 (depth: 8.0)
  skipping low-depth run: 10564.NQLWA6VI.134305 (depth: 2166.0)
  skipping low-depth run: 10317.X00215556.156882 (depth: 532.0)
kept 3240 samples out of 6744 ambiguous samples.

In [83]:
# subtract all ambiguous sample from present, then add back kept ones
ambig_runs = {run for runs in ambig.values() for run in runs}
unambiguous = present - ambig_runs

print(f"{len(present)} total samples")
print(f"{len(ambig_runs)} ambiguous samples")
print(f"{len(unambiguous)} unambiguous samples")

for sample_id in unambiguous:
    if is_control(sample_id):
        print(f"skipping control run: {sample_id}")
        continue
    if depth(sample_id) < clip_count:
        print(f"  skipping low-depth run: {sample_id} (depth: {depth(sample_id)})")
        continue
    keep.add(sample_id)

print(f"{len(keep)} total samples after filtering.")

42500 total samples
6744 ambiguous samples
35756 unambiguous samples
  skipping low-depth run: 894.YY1830.lane2.NoIndex.L002.128416 (depth: 13.0)
  skipping low-depth run: 10317.000012201.128816 (depth: 2703.0)
  skipping low-depth run: 12906.Milk.T6.171.132803 (depth: 4816.0)
  skipping low-depth run: 1958.Antibioticday5.10.86.128677 (depth: 1003.0)
  skipping low-depth run: 10317.000053363.132132 (depth: 3069.0)
  skipping low-depth run: 10093.s3d42p6.127811 (depth: 1134.0)
  skipping low-depth run: 1958.Preantibiotic.4.62.128677 (depth: 1414.0)
  skipping low-depth run: 10317.000042933.132132 (depth: 3035.0)
  skipping low-depth run: 11113.1122.127587 (depth: 25.0)
  skipping low-depth run: 10317.000011077.128816 (depth: 3734.0)
  skipping low-depth run: 10317.000016182.128434 (depth: 2560.0)
  skipping low-depth run: 10317.000040346.128247 (depth: 1498.0)
  skipping low-depth run: 10317.000015195.128434 (depth: 4.0)
skipping control run: 11914.St.neg.GLD065.155591
  skipping low-depth run: 10317.000037939.129489 (depth: 2921.0)
  skipping low-depth run: 10317.000059036.132132 (depth: 3421.0)
  skipping low-depth run: 10317.000014793.128789 (depth: 3435.0)
  skipping low-depth run: 10323.P05K10.F.0512B.131002 (depth: 11.0)
  skipping low-depth run: 10093.s3d7p7.127811 (depth: 3621.0)
  skipping low-depth run: 10317.000065793.131202 (depth: 3065.0)
  skipping low-depth run: 10469.Meta.c08.wk16.130664 (depth: 3083.0)
skipping control run: 11914.St.neg.GLD126.155591
  skipping low-depth run: 894.SL821.lane3.NoIndex.L003.128416 (depth: 4405.0)
  skipping low-depth run: 10317.X00172775.135998 (depth: 20.0)
skipping control run: 11914.St.neg.GLD002.155591
  skipping low-depth run: 10317.000017756.128434 (depth: 4568.0)
  skipping low-depth run: 10317.000023965.128247 (depth: 2181.0)
  skipping low-depth run: 1939.100016.128431 (depth: 4367.0)
  skipping low-depth run: 10317.000071846.132367 (depth: 2693.0)
  skipping low-depth run: 10317.000054085.132132 (depth: 3292.0)
  skipping low-depth run: 11888.1019.133401 (depth: 4794.0)
  skipping low-depth run: 10093.s1d28p6.127811 (depth: 2779.0)
  skipping low-depth run: 10469.Meta.c33.wk11.130664 (depth: 3336.0)
  skipping low-depth run: 10317.000028207.128247 (depth: 1675.0)
  skipping low-depth run: 10317.X00214884.156882 (depth: 25.0)
  skipping low-depth run: 10317.000028746.131424 (depth: 4.0)
  skipping low-depth run: 10317.X00191396.139280 (depth: 4987.0)
  skipping low-depth run: 10317.000052344.132132 (depth: 4245.0)
  skipping low-depth run: 10323.K17W18.0911B.131002 (depth: 4.0)
  skipping low-depth run: 10469.Meta.p23.wk11.130664 (depth: 2940.0)
  skipping low-depth run: 10317.X00168619.135985 (depth: 3238.0)
  skipping low-depth run: 10323.P51Y69.F.0212A.2.131002 (depth: 700.0)
  skipping low-depth run: 10469.Meta.p03.wk08.130664 (depth: 3659.0)
  skipping low-depth run: 10317.000009694.128800 (depth: 4053.0)
  skipping low-depth run: 10469.Meta.p20.wk06.130664 (depth: 3184.0)
  skipping low-depth run: 10317.000027664.131460 (depth: 1571.0)
  skipping low-depth run: 10317.000049961.129086 (depth: 2971.0)
  skipping low-depth run: 10317.000100338.128320 (depth: 11.0)
  skipping low-depth run: 16036.ABA.D.59.220097 (depth: 9.0)
  skipping low-depth run: 10469.Meta.p02.wk30.130664 (depth: 2550.0)
skipping control run: 11914.St.neg.GLD049.155591
  skipping low-depth run: 10469.Meta.p19.wk08.130664 (depth: 1871.0)
  skipping low-depth run: 10317.000072253.129086 (depth: 4128.0)
  skipping low-depth run: 10317.000154461.135989 (depth: 4810.0)
  skipping low-depth run: 10317.000010690.128816 (depth: 2406.0)
  skipping low-depth run: 894.UY661.lane3.NoIndex.L003.128416 (depth: 2698.0)
  skipping low-depth run: 10323.K03K04.0212B.131002 (depth: 2837.0)
  skipping low-depth run: 10323.L29W30.0212B.131002 (depth: 5.0)
  skipping low-depth run: 10317.000011181.128816 (depth: 1984.0)
  skipping low-depth run: 1958.Preantibiotic.9.67.128677 (depth: 1400.0)
skipping control run: 11914.St.neg.GLD088.155591
  skipping low-depth run: 10317.000058485.132132 (depth: 4268.0)
  skipping low-depth run: 10317.000067814.130783 (depth: 35.0)
  skipping low-depth run: 16036.ABA.D.137.220097 (depth: 770.0)
  skipping low-depth run: 10317.000155642.135998 (depth: 1263.0)
  skipping low-depth run: 10317.000001702.128434 (depth: 3791.0)
  skipping low-depth run: 10317.000058475.131418 (depth: 4588.0)
  skipping low-depth run: 10317.000073306.128704 (depth: 5.0)
  skipping low-depth run: 1939.121969.128431 (depth: 3878.0)
  skipping low-depth run: 10317.000053348.131418 (depth: 583.0)
  skipping low-depth run: 16036.ABA.D.132.220097 (depth: 4097.0)
  skipping low-depth run: 10317.000038274.132132 (depth: 1279.0)
  skipping low-depth run: 10317.000020718.128800 (depth: 4806.0)
  skipping low-depth run: 10317.000086640.130690 (depth: 6.0)
  skipping low-depth run: 10317.000005879.131012 (depth: 10.0)
  skipping low-depth run: 1924.Sadowsky.86.128948 (depth: 4.0)
  skipping low-depth run: 10317.000058478.131418 (depth: 3561.0)
  skipping low-depth run: 10323.K15B02.F.0312B.131002 (depth: 4.0)
  skipping low-depth run: 10317.X00166777.139313 (depth: 6.0)
  skipping low-depth run: 1958.Antibioticday1.7.73.128677 (depth: 558.0)
  skipping low-depth run: 10469.Meta.p14.wk30.130664 (depth: 990.0)
  skipping low-depth run: 10768.000030083.155435 (depth: 1464.0)
  skipping low-depth run: 10317.000022117.128800 (depth: 4998.0)
  skipping low-depth run: 894.UY776.lane3.NoIndex.L003.128416 (depth: 4837.0)
  skipping low-depth run: 16036.ABA.D.171.220097 (depth: 4125.0)
  skipping low-depth run: 10317.000074216.130690 (depth: 1514.0)
  skipping low-depth run: 10317.000147494.135998 (depth: 1971.0)
  skipping low-depth run: 10317.000054138.132132 (depth: 3617.0)
  skipping low-depth run: 10093.s1d42p2L11.127811 (depth: 9.0)
  skipping low-depth run: 10469.Meta.p20.wk08.130664 (depth: 1905.0)
  skipping low-depth run: 10317.000039906.128247 (depth: 3731.0)
  skipping low-depth run: 10317.000089354.130690 (depth: 1712.0)
  skipping low-depth run: 10469.Meta.p01.wk09.130664 (depth: 3996.0)
  skipping low-depth run: 894.GV1016.lane5.NoIndex.L005.128416 (depth: 4.0)
  skipping low-depth run: 10469.Meta.p19.wk06.130664 (depth: 2467.0)
  skipping low-depth run: 10317.000016216.128434 (depth: 3108.0)
  skipping low-depth run: 10532.9ed6ca18.aff3.4795.ab4a.1b7af3b839a9.128763 (depth: 4265.0)
  skipping low-depth run: 10317.000037983.131754 (depth: 3304.0)
skipping control run: 11914.St.neg.COPD1046.2.155591
  skipping low-depth run: 10317.000051555.131793 (depth: 1897.0)
  skipping low-depth run: 10317.000040104.128247 (depth: 3341.0)
  skipping low-depth run: 10469.Meta.p24.wk08.130664 (depth: 4107.0)
  skipping low-depth run: 10317.000045025.132132 (depth: 2987.0)
  skipping low-depth run: 10317.000054230.132132 (depth: 3986.0)
  skipping low-depth run: 10317.000047773.132132 (depth: 2589.0)
  skipping low-depth run: 10317.000068233.131582 (depth: 973.0)
  skipping low-depth run: 10317.000032618.127156 (depth: 2343.0)
  skipping low-depth run: 10317.000076409.130337 (depth: 90.0)
  skipping low-depth run: 10317.000067828.131582 (depth: 3310.0)
  skipping low-depth run: 10317.000050256.132132 (depth: 2730.0)
  skipping low-depth run: 10317.000020773.128800 (depth: 4741.0)
  skipping low-depth run: 894.UY15.lane3.NoIndex.L003.128416 (depth: 4250.0)
  skipping low-depth run: 10317.000031319.128247 (depth: 4151.0)
  skipping low-depth run: 10317.000033294.131418 (depth: 3344.0)
  skipping low-depth run: 10317.000020772.128800 (depth: 4869.0)
  skipping low-depth run: 10317.000060291.132132 (depth: 3490.0)
  skipping low-depth run: 894.UY143.lane3.NoIndex.L003.128416 (depth: 3995.0)
  skipping low-depth run: 10317.000158019.135998 (depth: 1818.0)
  skipping low-depth run: 10317.000046272.131161 (depth: 2959.0)
  skipping low-depth run: 10317.000011192.128484 (depth: 4150.0)
  skipping low-depth run: 10317.000032977.128247 (depth: 3776.0)
  skipping low-depth run: 10469.Meta.c13.wk09.130664 (depth: 2836.0)
  skipping low-depth run: 10317.000021608.128623 (depth: 733.0)
  skipping low-depth run: 10317.000089323.128309 (depth: 445.0)
  skipping low-depth run: 10317.000066819.129086 (depth: 2906.0)
  skipping low-depth run: 10317.000075896.128309 (depth: 1866.0)
  skipping low-depth run: 10469.Meta.c07.wk11.130664 (depth: 3119.0)
  skipping low-depth run: 10469.Meta.p04.MC.130664 (depth: 4091.0)
  skipping low-depth run: 10469.Meta.c07.wk08.130664 (depth: 1917.0)
  skipping low-depth run: 10317.000053389.132132 (depth: 2955.0)
  skipping low-depth run: 10317.000053405.132132 (depth: 1948.0)
  skipping low-depth run: 16036.ABA.I.412.220097 (depth: 4954.0)
  skipping low-depth run: 10317.000059083.132132 (depth: 2057.0)
  skipping low-depth run: 10317.000107344.133200 (depth: 1365.0)
  skipping low-depth run: 10317.000092665.129317 (depth: 2680.0)
  skipping low-depth run: 10469.Meta.c12.wk05.130664 (depth: 2962.0)
  skipping low-depth run: 894.UY800.lane3.NoIndex.L003.128416 (depth: 4852.0)
  skipping low-depth run: 10317.000033246.131754 (depth: 4922.0)
  skipping low-depth run: 10323.P51Y69.F.0712A.131002 (depth: 10.0)
  skipping low-depth run: 10317.000072421.129086 (depth: 2311.0)
  skipping low-depth run: 10469.Meta.c10.wk04.130664 (depth: 2774.0)
  skipping low-depth run: 10317.000021969.128800 (depth: 3408.0)
  skipping low-depth run: 10317.000003171.127045 (depth: 3772.0)
  skipping low-depth run: 10317.000092725.129317 (depth: 2329.0)
  skipping low-depth run: 10469.Meta.p01.wk06.130664 (depth: 4202.0)
  skipping low-depth run: 10317.000058500.132132 (depth: 2693.0)
  skipping low-depth run: 894.UY162.lane3.NoIndex.L003.128416 (depth: 4502.0)
  skipping low-depth run: 10317.000059198.132132 (depth: 4430.0)
  skipping low-depth run: 10323.K03K04.F.0512A.131002 (depth: 17.0)
  skipping low-depth run: 10317.000032976.128247 (depth: 2921.0)
  skipping low-depth run: 11113.121.131672 (depth: 4606.0)
  skipping low-depth run: 10323.K05G02.0611A.131002 (depth: 17.0)
  skipping low-depth run: 1998.SKSTL0201.127975 (depth: 4437.0)
  skipping low-depth run: 16036.ABA.R.255.220097 (depth: 23.0)
  skipping low-depth run: 10532.c87aa886.d2cf.432a.b38b.f40c01cb1965.128763 (depth: 4974.0)
  skipping low-depth run: 10317.000001916.129436 (depth: 11.0)
  skipping low-depth run: 1958.Antibioticday1.6.72.128677 (depth: 433.0)
  skipping low-depth run: 10317.000013945.128789 (depth: 4804.0)
  skipping low-depth run: 10469.Meta.c13.MC.130664 (depth: 3713.0)
  skipping low-depth run: 10317.000059197.132132 (depth: 4788.0)
  skipping low-depth run: 10317.000038483.128247 (depth: 4778.0)
  skipping low-depth run: 10317.000151274.135989 (depth: 4077.0)
  skipping low-depth run: 10317.000015562.128800 (depth: 3627.0)
  skipping low-depth run: 10317.000039862.131774 (depth: 4676.0)
skipping control run: 13338.St.neg.GLD137.135602
  skipping low-depth run: 10469.Meta.c09.wk05.130664 (depth: 3205.0)
  skipping low-depth run: 10317.000017324.128789 (depth: 3508.0)
skipping control run: 11914.St.neg.GLD017.155591
  skipping low-depth run: 10317.000052414.131418 (depth: 4292.0)
skipping control run: 11914.St.neg.LHM014.2.155591
skipping control run: 11914.St.neg.COPD1019.2.155591
  skipping low-depth run: 10317.000012962.128816 (depth: 3220.0)
  skipping low-depth run: 10317.000014473.129024 (depth: 2067.0)
  skipping low-depth run: 10469.Meta.c08.MC.130664 (depth: 3261.0)
  skipping low-depth run: 12906.Non.T0.670.132803 (depth: 3918.0)
  skipping low-depth run: 10317.000115462.135636 (depth: 4522.0)
  skipping low-depth run: 10317.000034257.131134 (depth: 4657.0)
  skipping low-depth run: 10317.000050335.131418 (depth: 4344.0)
  skipping low-depth run: 10317.000014381B.128189 (depth: 2251.0)
  skipping low-depth run: 10469.Meta.p16.MC.130664 (depth: 3084.0)
  skipping low-depth run: 10317.000030554.128247 (depth: 2757.0)
  skipping low-depth run: 10317.000047157.132132 (depth: 2663.0)
  skipping low-depth run: 11404.000063473.130790 (depth: 3138.0)
  skipping low-depth run: 10317.000032799.128247 (depth: 3055.0)
  skipping low-depth run: 10093.s1d1p2.127811 (depth: 1934.0)
  skipping low-depth run: 10317.000039899.128247 (depth: 4781.0)
  skipping low-depth run: 10317.000028511.128247 (depth: 2377.0)
  skipping low-depth run: 10317.000050172.132132 (depth: 2309.0)
  skipping low-depth run: 10317.000074253.133908 (depth: 2841.0)
  skipping low-depth run: 10317.000050234.131418 (depth: 3546.0)
skipping control run: 13338.St.neg.GLD047.135602
  skipping low-depth run: 10317.000028395.129073 (depth: 875.0)
  skipping low-depth run: 10317.000071557.130337 (depth: 630.0)
  skipping low-depth run: 894.UY179.lane3.NoIndex.L003.128416 (depth: 4325.0)
  skipping low-depth run: 10317.000052450.131418 (depth: 3507.0)
  skipping low-depth run: 10317.000068088.130919 (depth: 1453.0)
  skipping low-depth run: 1939.122099.b.128431 (depth: 3997.0)
  skipping low-depth run: 10317.000115489.135636 (depth: 4711.0)
  skipping low-depth run: 11402.MC005.129860 (depth: 45.0)
  skipping low-depth run: 10469.Meta.c33.wk18.130664 (depth: 2731.0)
  skipping low-depth run: 10522.2600.54892.129876 (depth: 4994.0)
  skipping low-depth run: 10469.Meta.c12.wk09.130664 (depth: 3017.0)
  skipping low-depth run: 10317.000020644.128800 (depth: 4304.0)
  skipping low-depth run: 10323.K11Y02.F.0212A.131002 (depth: 12.0)
  skipping low-depth run: 10317.000114450.134138 (depth: 823.0)
  skipping low-depth run: 10317.000041995.128247 (depth: 1565.0)
  skipping low-depth run: 10317.000093629.129317 (depth: 3187.0)
  skipping low-depth run: 10469.Meta.p04.wk30.130664 (depth: 2580.0)
  skipping low-depth run: 10317.000053425.131418 (depth: 4539.0)
  skipping low-depth run: 10323.L29W30.0811A.131002 (depth: 2932.0)
  skipping low-depth run: 10317.000046073.131793 (depth: 935.0)
  skipping low-depth run: 10093.s3d14p6.127811 (depth: 3816.0)
  skipping low-depth run: 10317.000005935.131494 (depth: 10.0)
  skipping low-depth run: 10317.000015193.128434 (depth: 4.0)
  skipping low-depth run: 10323.B46G19.F.0212A.131002 (depth: 4780.0)
  skipping low-depth run: 10469.Meta.p05.wk05.130664 (depth: 4653.0)
  skipping low-depth run: 1924.Sadowsky.1.128948 (depth: 13.0)
  skipping low-depth run: 2182.ZX12A.131622 (depth: 146.0)
  skipping low-depth run: 16036.ABA.R.297.220097 (depth: 2877.0)
  skipping low-depth run: 10317.000068275.129086 (depth: 3552.0)
  skipping low-depth run: 10317.000038431.128247 (depth: 4660.0)
  skipping low-depth run: 10317.000112791.132143 (depth: 20.0)
  skipping low-depth run: 10317.000041781.131418 (depth: 4054.0)
skipping control run: 13338.St.neg.GLD063.135602
  skipping low-depth run: 10317.000030577.132132 (depth: 2355.0)
skipping control run: 11914.St.neg.LHM027.2.155591
  skipping low-depth run: 10317.000042655.131418 (depth: 3342.0)
  skipping low-depth run: 10317.000058388.130092 (depth: 39.0)
  skipping low-depth run: 10317.000042632.132132 (depth: 4544.0)
  skipping low-depth run: 16036.ABA.I.416.220097 (depth: 4330.0)
  skipping low-depth run: 10317.000033007.128247 (depth: 3391.0)
  skipping low-depth run: 894.UY796.lane3.NoIndex.L003.128416 (depth: 4886.0)
  skipping low-depth run: 10317.X00173880.139313 (depth: 27.0)
  skipping low-depth run: 11402.MC116.129860 (depth: 1524.0)
  skipping low-depth run: 16036.ABA.R.250.220097 (depth: 2159.0)
  skipping low-depth run: 16036.ABA.D.77.220097 (depth: 2855.0)
  skipping low-depth run: 10093.s1d3p11.127811 (depth: 3447.0)
  skipping low-depth run: 10469.Meta.c27.wk30.130664 (depth: 2398.0)
  skipping low-depth run: 10317.000044553.132132 (depth: 3547.0)
  skipping low-depth run: 10469.Meta.p23.wk30.130664 (depth: 1597.0)
  skipping low-depth run: 10317.000054084.132132 (depth: 2766.0)
  skipping low-depth run: 10317.000154632.135998 (depth: 2474.0)
  skipping low-depth run: 10317.000037605.128247 (depth: 4861.0)
  skipping low-depth run: 10317.000030466.131418 (depth: 4042.0)
  skipping low-depth run: 10469.Meta.p16.wk16.130664 (depth: 3882.0)
  skipping low-depth run: 894.UY128.lane3.NoIndex.L003.128416 (depth: 4947.0)
  skipping low-depth run: 10317.000020790.131793 (depth: 437.0)
  skipping low-depth run: 10317.000052010.128668 (depth: 4502.0)
  skipping low-depth run: 10317.000006767.128816 (depth: 379.0)
  skipping low-depth run: 10317.000043003.128247 (depth: 2336.0)
  skipping low-depth run: 16036.ABA.I.407.220097 (depth: 1030.0)
  skipping low-depth run: 10093.s2d42p6.127811 (depth: 2324.0)
  skipping low-depth run: 1998.SKSTL0087.127975 (depth: 3908.0)
  skipping low-depth run: 10317.000071461.129086 (depth: 2541.0)
  skipping low-depth run: 10317.000011103.128816 (depth: 3954.0)
  skipping low-depth run: 10317.000051992.127156 (depth: 4315.0)
  skipping low-depth run: 10317.000052069.131763 (depth: 4781.0)
  skipping low-depth run: 10317.000050177.132132 (depth: 4690.0)
  skipping low-depth run: 10317.000029474.129489 (depth: 3954.0)
  skipping low-depth run: 10317.000045023.131161 (depth: 4756.0)
  skipping low-depth run: 10317.000053404.132132 (depth: 1875.0)
  skipping low-depth run: 10469.Meta.c27.wk08.130664 (depth: 4143.0)
  skipping low-depth run: 10317.000041874.128247 (depth: 4275.0)
  skipping low-depth run: 10317.X00191390.139280 (depth: 4796.0)
  skipping low-depth run: 10469.Meta.c29.wk16.130664 (depth: 3882.0)
  skipping low-depth run: 10469.Meta.c27.wk11.130664 (depth: 2761.0)
  skipping low-depth run: 10469.Meta.p05.wk18.130664 (depth: 2361.0)
  skipping low-depth run: 1924.Sadowsky.83.128948 (depth: 4.0)
  skipping low-depth run: 10323.K11Y02.0412A.131002 (depth: 15.0)
skipping control run: 11914.St.neg.COPD1065.155591
  skipping low-depth run: 10317.000041677.132132 (depth: 2934.0)
  skipping low-depth run: 10317.000010895.128816 (depth: 3160.0)
  skipping low-depth run: 10469.Meta.p04.wk04.130664 (depth: 1503.0)
  skipping low-depth run: 10317.000054328.131418 (depth: 4391.0)
  skipping low-depth run: 10317.000047028.129440 (depth: 180.0)
  skipping low-depth run: 10323.R03L04.F.0312B.131002 (depth: 11.0)
  skipping low-depth run: 10317.000005960.128816 (depth: 4345.0)
  skipping low-depth run: 10317.000059199.132132 (depth: 3339.0)
  skipping low-depth run: 10317.000059040.132132 (depth: 3097.0)
  skipping low-depth run: 10093.s2d35p6L11.127811 (depth: 1308.0)
  skipping low-depth run: 10317.000041973.128247 (depth: 3114.0)
skipping control run: 13338.St.neg.GLD159.135602
  skipping low-depth run: 10469.Meta.p03.wk30.130664 (depth: 2820.0)
  skipping low-depth run: 10317.000031846.131774 (depth: 4823.0)
  skipping low-depth run: 894.OR423.lane3.NoIndex.L003.128416 (depth: 4320.0)
  skipping low-depth run: 11349.sample3173.129879 (depth: 3568.0)
  skipping low-depth run: 10469.Meta.c10.wk08.130664 (depth: 3961.0)
  skipping low-depth run: 10317.000011193.127160 (depth: 4062.0)
  skipping low-depth run: 10317.000036964.131424 (depth: 3193.0)
  skipping low-depth run: 10317.X00215060.147023 (depth: 4087.0)
  skipping low-depth run: 10317.000012184.128816 (depth: 3177.0)
  skipping low-depth run: 10317.000032840.128247 (depth: 774.0)
  skipping low-depth run: 10317.000040328.128247 (depth: 2115.0)
  skipping low-depth run: 12906.Milk.T2.417.132803 (depth: 140.0)
  skipping low-depth run: 10469.Meta.c06.MC.130664 (depth: 3086.0)
  skipping low-depth run: 10323.Y60G05.F.0811B.131002 (depth: 3362.0)
skipping control run: 11914.St.neg.GLD115.155591
  skipping low-depth run: 10317.000038299.131774 (depth: 2472.0)
  skipping low-depth run: 10317.X00191369.139280 (depth: 4538.0)
  skipping low-depth run: 10317.000030701.128247 (depth: 1750.0)
skipping control run: 13338.St.neg.GLD086.135602
  skipping low-depth run: 10317.000073869.129086 (depth: 1300.0)
  skipping low-depth run: 10317.000036152.132132 (depth: 4410.0)
  skipping low-depth run: 10317.000017319.128800 (depth: 2321.0)
skipping control run: 13338.St.neg.DM063.1.135602

In [84]:
from biom.util import biom_open
filter_fn = lambda val, id_, md: id_ in keep
new_table = table.filter(filter_fn, inplace=False)
out_path = "cleaned_table.biom"
with biom_open(out_path, "w") as f:
    new_table.to_hdf5(f, "cleaned table")
print(f"Wrote cleaned BIOM table to: {out_path}")

Wrote cleaned BIOM table to: cleaned_table.biom

In [ ]:
# import numpy as np
# from biom.table import Table
# data = np.asarray([[0, 0, 1], [1, 3, 42]])
# table = Table(data, ['O1', 'O2'], ['S1', 'S2', 'S3'],
#               [{'full_genome_available': True},
#                {'full_genome_available': False}],
#               [{'sample_type': 'a'}, {'sample_type': 'a'},
#                {'sample_type': 'b'}])
# print(table)
# kept = set()
# kept.add('S1')
# kept.add('S2')
# filter_fn = lambda val, id_, md: id_ in kept
# new_table = table.filter(filter_fn, inplace=False)
# print(new_table)

# Constructed from biom file
#OTU ID	S1	S2	S3
O1	0.0	0.0	1.0
O2	1.0	3.0	42.0
# Constructed from biom file
#OTU ID	S1	S2
O1	0.0	0.0
O2	1.0	3.0

In [5]:
samples = ["10317.000030031.129073", "10469.Meta.p05.wk08.130664", "894.UY150.lane3.NoIndex.L003.128416", "10532.03a27c57.cf57.417a.90fe.5b9d5ffb32c0.128763"]

mapping = {c: ".".join(c.split(".")[:-1]) for c in samples}
mapping

{'10317.000030031.129073': '10317.000030031',
 '10469.Meta.p05.wk08.130664': '10469.Meta.p05.wk08',
 '894.UY150.lane3.NoIndex.L003.128416': '894.UY150.lane3.NoIndex.L003',
 '10532.03a27c57.cf57.417a.90fe.5b9d5ffb32c0.128763': '10532.03a27c57.cf57.417a.90fe.5b9d5ffb32c0'}

In [1]:
from biom import load_table
from skbio import TreeNode

table = load_table("../data/v4_stool/v4_stool_cleaned_filtered_biom/feature-table.biom")
tree  = TreeNode.read("../crawford.tre")  # or your own tree

otu_ids = set(table.ids(axis='observation'))          # OTU/ASV IDs from BIOM
tree_ids = set(tip.name for tip in tree.tips())       # tip labels from tree

print("n_otus_in_table:", len(otu_ids))
print("n_tips_in_tree:", len(tree_ids))
print("intersection:", len(otu_ids & tree_ids))

# sanity check: does tree fully cover table?
print("all_otus_covered?", otu_ids.issubset(tree_ids))

n_otus_in_table: 1875457
n_tips_in_tree: 365
intersection: 0
all_otus_covered? False

In [3]:
from skbio import TreeNode

tree = TreeNode.read("tree.nwk")

for i, tip in enumerate(tree.tips()):
    print(tip.name)
    if i == 4:   # just print first 5
        break

GB-GCA-003568775.1-MWMI01000008.1
GB-GCA-001552015.1-CP010514.1
GB-GCA-000008085.1-AE017199.1
TAGCCGCACCCCAAGTGGTAGTCATTATTATTGGGCTTAAAGTGTTCGTAGCCGGGCCTGAAAGTCCGCTGTGAAATCCAAGCGCTCAAC
TACCCGCGCCACGAGTGGTGATCGCGATTATTGGGCCTAAAGGGTTCGTAGCCGGTTTGGCAAGTTCCTGGTGAAATCTTTCAGCTAACTGAAAGGCGTG

In [10]:
count150 = 0
for i, tip in enumerate(tree.tips()):
    if len(tip.name) == 150:
        count150 += 1

print("n_tips_with_150_char_names:", count150)

n_tips_with_150_char_names: 8927883

In [11]:
from biom import load_table
table = load_table("../data/v4_stool/v4_stool_cleaned_filtered_biom/feature-table.biom")
otu_ids = set(table.ids(axis='observation'))          # OTU/ASV IDs from BIOM
tree_ids = set(tip.name for tip in tree.tips())       # tip labels from tree

print("n_otus_in_table:", len(otu_ids))
print("n_tips_in_tree:", len(tree_ids))
print("intersection:", len(otu_ids & tree_ids))

# sanity check: does tree fully cover table?
print("all_otus_covered?", otu_ids.issubset(tree_ids))

n_otus_in_table: 1875457
n_tips_in_tree: 23450268
intersection: 1875457
all_otus_covered? True

In [ ]:
from biom import load_table
import unifrac
import numpy as np

# 1. Load table
table = load_table("../data/v4_stool/v4_stool_cleaned_filtered_biom/feature-table.biom")

# Ordered OTU/ASV IDs (150bp sequences) – KEEP AS ARRAY, NOT set()
otu_ids = table.ids(axis='observation')           # length = n_features
sample_ids = table.ids(axis='sample')             # length = n_samples

print("n_features:", len(otu_ids))
print("n_samples :", len(sample_ids))

# 2. Pick two samples, e.g. first two columns
samp0_vec = table[:, 0].toarray().flatten()       # shape (n_features,)
samp1_vec = table[:, 1].toarray().flatten()       # shape (n_features,)

print("samp0_vec shape:", samp0_vec.shape)
print("samp1_vec shape:", samp1_vec.shape)

# 3. Compute UniFrac distance between these two samples
TREE_FP = "tree.nwk"  # path to your (possibly huge) GG2 ASV tree

dist01 = unifrac.unweighted_dense_pair(
    otu_ids,      # ordered list/array of ASV IDs
    samp0_vec,    # counts for sample 0
    samp1_vec,    # counts for sample 1
    TREE_FP
)

print("UniFrac(s0, s1) =", dist01)

n_features: 1875457
n_samples : 36668
samp0_vec shape: (1875457,)
samp1_vec shape: (1875457,)

AttributeError: module 'unifrac' has no attribute 'unweighted_sparse_pair'

In [50]:
# read metadata file txt 
import pandas as pd
import difflib

def load_metadata(metadata_fp: str, id_col: str) -> pd.DataFrame:
    """Load metadata file as Pandas DataFrame."""
    try:
        meta = pd.read_csv(metadata_fp, sep="\t", dtype={id_col: str})
    except Exception as e:
        raise ValueError(f"Failed to read metadata file '{metadata_fp}': {e}")
    return meta

df = load_metadata("../data/test_set/human_test_set_v4_10317_stool_cleaned_filtered/sample-metadata.txt", id_col="#SampleID")


#read from tsv
a = open("../data/test_set/human_test_set_v4_10317_stool_cleaned_filtered/sample-metadata.txt").readlines()[0]
b = a.strip().split('\t')
print(b)

# # get headers
# columns = df.columns.tolist()
# print('number of metadata columns:', len(columns))
# print("Metadata columns:", "\n".join(columns))

# query = "Colonic"

# col = [s for s in columns if query in s]
# print("Direct matches for column name:", col)

# matches = difflib.get_close_matches(query, columns, n=3, cutoff=0.2)

# print("Close matches for column name:", matches)

['#SampleID', 'specialized_diet_unspecified', 'mental_illness_type_anorexia_nervosa', 'artificial_sweeteners', 'last_travel', 'bowel_movement_frequency', 'physical_specimen_remaining', 'vegetable_frequency', 'olive_oil', 'allergic_to_peanuts', 'ready_to_eat_meals_frequency', 'public', 'fruit_frequency', 'allergic_to_i_have_no_food_allergies_that_i_know_of', 'seafood_frequency', 'types_of_plants', 'pku', 'host_weight', 'title', 'mental_illness_type_unspecified', 'whole_eggs', 'multivitamin', 'milk_cheese_frequency', 'dog', 'diabetes', 'other_supplement_frequency', 'longitude', 'autoimmune', 'sugary_sweets_frequency', 'thyroid', 'non_food_allergies_drug_eg_penicillin', 'dna_extracted', 'teethbrushing_frequency', 'migraine', 'cat', 'vivid_dreams', 'host_taxid', 'chickenpox', 'level_of_education', 'lung_disease', 'fungal_overgrowth', 'alcohol_types_beercider', 'kidney_disease', 'non_food_allergies_beestings', 'non_food_allergies_poison_ivyoak', 'host_height', 'sample_type', 'env_package', 'alcohol_types_spiritshard_alcohol', 'exercise_location', 'specialized_diet_fodmap', 'specialized_diet_modified_paleo_diet', 'empo_2', 'specialized_diet_other_restrictions_not_described_here', 'sibo', 'host_body_mass_index', 'high_fat_red_meat_frequency', 'mental_illness_type_schizophrenia', 'state', 'livingwith', 'skin_condition', 'cancer_treatment', 'allergic_to_shellfish', 'cosmetics_frequency', 'clinical_condition', 'host_subject_id', 'meat_eggs_frequency', 'mental_illness_type_depression', 'host_body_site', 'one_liter_of_water_a_day_frequency', 'env_material', 'smoking_frequency', 'taxon_id', 'non_food_allergies_sun', 'ibs', 'weight_change', 'host_height_units', 'host_weight_units', 'softener', 'geo_loc_name', 'diet_type', 'frozen_dessert_frequency', 'host_body_habitat', 'milk_substitute_frequency', 'body_site', 'pregnant', 'host_common_name', 'physical_specimen_location', 'acid_reflux', 'anonymized_name', 'specialized_diet_halaal', 'acne_medication', 'flu_vaccine_date', 'red_meat_frequency', 'alcohol_types_unspecified', 'vitamin_d_supplement_frequency', 'bmi_cat', 'fermented_plant_frequency', 'mental_illness_type_bulimia_nervosa', 'empo_3', 'probiotic_frequency', 'alcohol_frequency', 'allergic_to_unspecified', 'nail_biter', 'gluten', 'description', 'race', 'exercise_frequency', 'add_adhd', 'age_cat', 'specialized_diet_i_do_not_eat_a_specialized_diet', 'deodorant_use', 'alcohol_types_sour_beers', 'flossing_frequency', 'prepared_meals_frequency', 'diabetes_type', 'roommates_in_study', 'epilepsy_or_seizure_disorder', 'dominant_hand', 'country_of_birth', 'drinks_per_session', 'allergic_to_tree_nuts', 'bowel_movement_quality', 'non_food_allergies_pet_dander', 'host_body_product', 'ibd', 'liver_disease', 'last_move', 'host_age', 'pool_frequency', 'sleep_duration', 'qiita_study_id', 'country_residence', 'ibd_diagnosis_refined', 'appendix_removed', 'salted_snacks_frequency', 'alcohol_types_white_wine', 'cancer', 'env_feature', 'antibiotic_history', 'specialized_diet_exclude_dairy', 'latitude', 'birth_year', 'poultry_frequency', 'pets_other', 'specialized_diet_kosher', 'mental_illness_type_bipolar_disorder', 'collection_timestamp', 'seasonal_allergies', 'specialized_diet_raw_food_diet', 'env_biome', 'host_age_normalized_years', 'empo_1', 'non_food_allergies_unspecified', 'cdiff', 'sex', 'lifestage', 'breastmilk_formula_ensure', 'lactose', 'alzheimers', 'alcohol_consumption', 'vitamin_b_supplement_frequency', 'homecooked_meals_frequency', 'drinking_water_source', 'asd', 'alcohol_types_red_wine', 'tonsils_removed', 'sugar_sweetened_drink_frequency', 'specialized_diet_exclude_refined_sugars', 'consume_animal_products_abx', 'csection', 'fed_as_infant', 'mental_illness', 'cardiovascular_disease', 'scientific_name', 'whole_grain_frequency', 'contraceptive', 'mental_illness_type_substance_abuse', 'specialized_diet_exclude_nightshades']

/var/folders/8s/djsz761n16x6mh8gpddd5dh40000gn/T/ipykernel_8384/3114817814.py:8: DtypeWarning: Columns (1,9,13,30,43,44,50,51,53,62,73,90,102,110,121,123,140,145,149,153,168,178) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv(metadata_fp, sep="\t", dtype={id_col: str})

In [ ]:
from collections import defaultdict
# read metadata file txt 
import pandas as pd
import difflib

def load_metadata(metadata_fp: str, id_col: str) -> pd.DataFrame:
    """Load metadata file as Pandas DataFrame."""
    try:
        meta = pd.read_csv(metadata_fp, sep="\t", dtype={id_col: str})
    except Exception as e:
        raise ValueError(f"Failed to read metadata file '{metadata_fp}': {e}")
    return meta

#df = load_metadata("../data/test_set/human_test_set_v4_10317_stool_cleaned_filtered/sample-metadata.txt", id_col="#SampleID")
df = load_metadata("../data/v4_stool/v4_stool_cleaned_filtered_biom/sample-metadata.tsv", id_col="#SampleID")

# get headers
columns = df.columns.tolist()
print("Metadata columns:", "\n".join(columns))
freq = defaultdict(int)
for x in df['qiita_study_id']:
    freq[x] += 1
results = sorted([(s, f) for s, f in freq.items()], key=lambda s: s[1], reverse=True)
main = results[:1]
others = results[1:]
print(main)
print(sum(f for _, f in others))

print(results)

# The problem, we need a train set that has collection invariance / batch effects that DO NOT EXIST in the test set.  Does that also mean the train set and the test set must also all be human and stool samples so all else is equal?  i.e the only difference that exists is collection noise?

# the assumption is that different study ids correspond to different collection processes

#

Metadata columns: #SampleID
sample_type
host_subject_id
qiita_study_id
physical_specimen_location
collection_timestamp
[(10317, 24626)]
15389
[(10317, 24626), (10184, 1924), (894, 1859), (2086, 1638), (2014, 1017), (11113, 969), (11349, 909), (12906, 687), (11888, 645), (10323, 605), (2401, 492), (10532, 474), (1998, 279), (11360, 274), (1939, 257), (16036, 230), (11123, 221), (10315, 193), (11402, 188), (2182, 159), (11625, 158), (10093, 157), (11212, 154), (10057, 138), (1924, 133), (10724, 130), (13010, 130), (10916, 118), (11914, 112), (11129, 106), (10564, 102), (10064, 93), (1880, 93), (1056, 92), (11404, 80), (11947, 77), (10342, 58), (11333, 56), (13338, 53), (11076, 50), (10469, 40), (10902, 39), (10904, 32), (10704, 30), (10461, 30), (15602, 29), (10407, 27), (10786, 24), (10522, 13), (10563, 12), (1684, 3)]

Unsupervised training 

study,human?,species_label, train,test_features, samplesN, comments
10317 36000 samples
10184,yes, host_scientific_name, yes,geo_loc_name, 1924, good for test we should add many human studies to claim invariance to
12906, yes, host_common_name, yes, geo_loc_name, 1017, good
2401,host_scientific_name, yes, geo_loc_name host_age, 492, good
10532, yes, host_scientific_name, yes, geo_loc_name, 474, good
1998, yes, host_scientific_name, yes, geo_loc_name only usa age, 279, good
1939, yes, host_scientific_name, yes, geo_loc_name age, gastrointest_disord a lot more, 257, good
16036, yes, host_scientific_name, yes, geo_loc_name, 230, good


#classify geo_loc_name we want better performance with embeddings than raw
#classify study_id we want worse performance with embeddings than raw

Plan
10317 + bottom half of the table above for unsupervised training of the embeddings encoder
Then test on the top half of the table for supervised tasks such as geo_loc_name and study_id classification
Use the rest of 10317 for supervised tasks such as age regression and chrons disease classification

Then punch out and say fuck it


invariant Holdouts 
2086, yes, host_scientific_name, yes, age geo_loc_name, 1638, good
2014, yes, host_scientific_name, yes, age geo_loc_name, 1017, good
11888, yes, host_common_name, yes, geo_loc_name host_age, 645, good


Core components:

📘 Encoding: Transformer-based sample embedding aligned to UniFrac phylogenetic distances

🔬 Datasets: American Gut Project (Qiita 10317, Deblur V4), plus several additional Qiita studies used to capture batch-effect variability.
All samples are human stool samples.

Study IDs included in the training dataset:

10184 (dark blue)

10532 (light blue)

2401 (orange)

16036 (light orange)

12906 (green)

1998 (light green)

1939 (red)

Holdouts for classification evaluation
(Each holdout study provides unseen samples with their own metadata distributions; all are human stool samples.)

2086 — host_scientific_name: yes, age: yes, geo_loc_name: yes, n = 1638, good

2014 — host_scientific_name: yes, age: yes, geo_loc_name: yes, n = 1017, good

11888 — host_common_name: yes, host_age: yes, geo_loc_name: yes, n = 645, good

⚙️ Preprocessing: BIOM → (sample_id, reads, 150bp nucleotides) triplet decomposition to (sample_id, embedding) for fine-grained modeling

📊 Evaluation: Distance correlation with UniFrac, downstream classifier accuracy on real data.

Goal:
Create uniform, biologically grounded representations of 16S microbiome data that enable cross-study compatibility and increased classifer accuracy on downstream health prediction tasks.

In [4]:
5350/30

178.33333333333334

In [2]:
'10317.000009111'.startswith('10517')

False

In [ ]:
#candidates country_of_birth ibd host_age ibd_diagnosis_refined acid_reflux

# max of host age filter for number and convert to int
import string


ages = [float(x) for x in df['host_age'] if x != "not provided" and x != "not collected"]
ages = [x for x in ages if x >= 0 and x <= 120] 

def host_age_label(x: string) -> int:
    
    if x >= 0 and x <= 120:
        return 1
    else:
        return 0

print(ages)
print(len(ages))
print("average host age:", sum(ages)/len(ages))
# print(ages)
print("max host age:", max(ages))
print("min host age:", min(ages))

ibd = [x for x in df['ibd'] if x == "Diagnosed by a medical professional (doctor, physician assistant)" or x == 'Diagnosed by an alternative medicine practitioner' or x == 'Self-diagnosed']
len(ibd)
print('len ibd:', len(ibd))

acid_reflux = [x for x in df['acid_reflux'] if x == "Diagnosed by a medical professional (doctor, physician assistant)" or x == 'Diagnosed by an alternative medicine practitioner' or x == 'Self-diagnosed']

def acid_reflux_label(x: str) -> int:
    if x == "Diagnosed by a medical professional (doctor, physician assistant)" or x == 'Diagnosed by an alternative medicine practitioner' or x == 'Self-diagnosed':
        return 1
    else:
        return 0

print("len acid reflux:", len(acid_reflux))
# country_of_birth = [x for x in df['country_of_birth']]
# print("set country of birth:", set(country_of_birth))
# print("len country of birth:", len(country_of_birth))


df[['country_of_birth', 'ibd', 'host_age', 'ibd_diagnosis_refined', 'acid_reflux']]

[74.9, 45.6, 64.3, 1.7, 30.5, 56.7, 36.5, 46.3, 58.0, 43.6, 66.8, 51.0, 61.4, 8.2, 78.0, 38.0, 59.1, 25.6, 71.3, 50.8, 59.8, 51.9, 34.2, 39.3, 37.0, 46.3, 67.1, 52.4, 70.2, 37.0, 41.9, 44.1, 25.1, 52.5, 3.9, 69.2, 46.6, 0.4, 73.0, 41.4, 60.6, 34.5, 37.7, 35.9, 40.7, 33.2, 41.1, 69.6, 34.9, 69.4, 48.1, 74.5, 40.3, 25.0, 48.0, 47.9, 63.8, 51.3, 72.4, 48.9, 53.6, 70.6, 52.1, 56.2, 75.9, 60.8, 27.0, 4.1, 56.6, 52.5, 26.6, 67.7, 36.1, 51.8, 60.5, 46.4, 72.2, 49.5, 45.1, 6.5, 51.9, 38.1, 48.4, 50.5, 30.6, 36.9, 35.9, 71.4, 10.3, 54.0, 27.2, 68.6, 60.3, 15.9, 33.1, 4.6, 55.5, 70.3, 30.5, 36.1, 55.0, 56.8, 48.5, 55.0, 74.0, 60.1, 27.4, 28.9, 74.2, 49.9, 40.6, 59.0, 33.1, 41.3, 30.6, 52.9, 22.0, 32.5, 47.2, 60.8, 70.8, 93.7, 65.3, 1.5, 43.1, 21.9, 0.9, 52.7, 51.6, 24.5, 53.9, 67.5, 15.2, 42.0, 41.9, 39.6, 24.3, 30.4, 57.0, 48.7, 79.8, 29.9, 61.7, 55.7, 57.5, 29.4, 13.6, 76.5, 79.4, 57.4, 27.1, 54.3, 40.6, 48.3, 69.4, 59.2, 51.9, 53.8, 30.2, 61.3, 2.4, 55.2, 50.9, 30.9, 7.9, 67.3, 64.2, 31.1, 21.6, 58.4, 58.6, 35.5, 31.1, 59.4, 44.3, 69.1, 51.4, 22.5, 21.6, 48.4, 66.7, 42.4, 41.0, 59.9, 42.8, 10.5, 6.0, 38.6, 43.8, 72.2, 41.7, 61.3, 11.2, 68.1, 58.4, 51.2, 42.4, 55.6, 55.6, 37.1, 64.5, 20.5, 35.8, 58.7, 61.0, 70.4, 60.8, 31.4, 48.8, 48.3, 58.2, 45.9, 41.3, 61.2, 45.6, 61.7, 67.5, 0.6, 56.0, 40.4, 15.6, 57.0, 22.4, 27.2, 28.1, 20.8, 43.9, 49.5, 64.2, 40.1, 24.4, 59.1, 42.2, 47.2, 25.4, 29.9, 40.0, 7.2, 42.7, 30.6, 23.6, 51.8, 26.8, 57.4, 23.8, 61.9, 28.5, 54.1, 72.0, 39.7, 43.2, 68.5, 73.7, 41.8, 65.4, 36.7, 58.7, 42.7, 28.7, 51.8, 55.7, 25.7, 52.3, 68.7, 45.8, 80.7, 34.0, 36.0, 40.6, 69.3, 57.2, 63.0, 23.6, 35.8, 68.7, 34.9, 11.8, 30.6, 56.4, 44.7, 53.8, 50.5, 51.6, 50.2, 44.1, 39.3, 42.2, 60.6, 48.2, 32.4, 42.8, 20.1, 48.8, 42.8, 19.8, 33.1, 38.1, 50.5, 26.8, 69.7, 61.8, 28.3, 72.5, 28.9, 38.5, 37.6, 55.1, 21.4, 34.8, 66.2, 65.2, 58.7, 57.7, 25.6, 57.6, 15.1, 59.3, 33.0, 49.4, 60.0, 24.9, 65.3, 19.4, 68.5, 24.8, 68.6, 71.9, 46.4, 5.7, 74.1, 21.8, 51.9, 59.6, 57.8, 64.4, 54.3, 10.6, 24.4, 22.7, 40.2, 53.8, 36.5, 38.7, 28.3, 26.5, 37.4, 53.7, 75.4, 45.1, 36.4, 35.0, 46.1, 69.7, 36.9, 58.5, 30.4, 48.8, 48.7, 34.8, 46.2, 53.1, 33.1, 24.3, 67.3, 62.6, 53.9, 48.2, 36.5, 24.5, 68.1, 59.9, 65.2, 76.2, 33.3, 40.3, 49.8, 44.0, 55.0, 21.5, 51.7, 64.1, 56.1, 36.4, 68.1, 29.7, 72.2, 38.1, 36.9, 52.8, 26.9, 57.2, 47.5, 32.0, 68.5, 32.0, 48.0, 73.4, 49.9, 38.6, 72.3, 38.3, 30.1, 33.4, 35.7, 56.8, 7.3, 55.8, 59.6, 74.0, 48.9, 68.1, 49.9, 39.8, 67.3, 61.5, 49.3, 21.5, 36.4, 42.7, 46.9, 36.7, 66.7, 71.9, 37.7, 69.4, 67.0, 26.8, 51.2, 51.2, 7.9, 41.7, 59.9, 35.6, 36.2, 51.5, 53.4, 34.6, 4.5, 58.3, 33.2, 2.4, 70.5, 45.8, 31.8, 60.1, 27.9, 31.2, 72.2, 72.6, 42.8, 53.4, 30.5, 1.1, 66.2, 25.4, 65.3, 21.2, 51.4, 1.2, 65.9, 33.8, 52.4, 27.5, 46.7, 18.7, 43.4, 27.4, 0.5, 58.8, 59.9, 51.5, 42.7, 39.4, 52.3, 56.8, 36.5, 68.9, 42.2, 70.2, 65.0, 25.2, 51.9, 70.8, 70.5, 53.6, 63.2, 60.2, 50.0, 55.7, 43.6, 31.0, 11.8, 59.5, 64.0, 69.6, 61.2, 79.7, 74.3, 51.9, 56.1, 50.6, 37.3, 72.9, 21.0, 53.9, 70.9, 25.1, 45.3, 72.1, 45.7, 47.8, 56.6, 76.2, 63.6, 60.0, 32.8, 57.3, 6.7, 56.7, 31.6, 37.3, 52.6, 55.5, 25.4, 59.6, 54.7, 55.8, 62.1, 50.2, 37.7, 19.3, 34.5, 26.1, 45.5, 1.0, 42.2, 33.4, 27.0, 49.1, 31.8, 39.3, 5.3, 22.5, 69.9, 75.1, 50.4, 34.6, 9.3, 36.3, 43.7, 60.3, 51.3, 50.0, 74.4, 66.8, 30.4, 47.1, 57.6, 71.0, 49.9, 66.6, 57.4, 40.2, 46.5, 57.5, 57.0, 50.4, 41.7, 33.9, 28.4, 30.3, 50.2, 30.1, 49.3, 33.4, 55.2, 68.6, 43.9, 7.0, 33.0, 49.4, 69.0, 27.2, 55.5, 48.3, 37.0, 48.9, 40.7, 46.3, 19.9, 55.1, 25.8, 66.6, 48.3, 46.5, 33.7, 56.9, 38.4, 24.7, 41.8, 53.7, 30.7, 42.1, 39.8, 63.0, 26.1, 45.1, 2.6, 33.4, 33.7, 51.5, 57.4, 38.2, 43.0, 82.6, 49.1, 61.1, 57.6, 28.0, 51.5, 56.2, 62.7, 74.6, 60.8, 55.6, 39.5, 59.1, 63.4, 65.0, 38.3, 39.7, 49.1, 9.4, 27.2, 57.4, 26.3, 57.9, 59.0, 67.3, 53.7, 27.6, 30.9, 38.3, 48.0, 66.8, 34.9, 39.5, 32.4, 47.3, 60.7, 37.7, 65.7, 40.9, 52.8, 32.8, 40.5, 68.1, 59.6, 72.9, 62.2, 61.1, 46.8, 77.6, 44.6, 39.8, 63.5, 57.3, 46.9, 54.3, 49.2, 74.1, 27.1, 47.2, 44.6, 34.5, 36.0, 59.9, 26.3, 37.2, 36.5, 25.4, 7.0, 54.8, 27.9, 47.2, 67.0, 64.9, 36.4, 68.7, 68.8, 65.7, 28.8, 69.7, 39.6, 31.3, 64.4, 55.3, 28.6, 61.9, 44.5, 63.3, 6.1, 51.3, 60.3, 22.2, 51.0, 61.5, 22.5, 21.0, 15.7, 25.6, 22.4, 60.4, 38.3, 46.6, 28.0, 58.7, 46.8, 52.8, 43.5, 65.3, 45.8, 34.9, 66.8, 46.7, 75.1, 44.3, 51.4, 81.4, 60.4, 22.8, 3.7, 70.1, 57.4, 26.6, 36.5, 21.9, 46.1, 53.0, 44.8, 31.5, 36.6, 42.1, 66.1, 34.5, 48.6, 21.6, 18.6, 60.8, 63.5, 43.2, 56.2, 19.6, 28.0, 37.2, 64.4, 39.3, 50.2, 50.5, 46.4, 44.5, 47.3, 57.2, 45.9, 25.3, 18.5, 40.7, 6.6, 57.1, 43.7, 61.9, 66.4, 48.2, 69.9, 32.5, 67.5, 49.7, 36.7, 22.7, 51.9, 48.6, 42.3, 40.0, 22.0, 35.5, 29.1, 53.7, 39.2, 48.1, 42.4, 27.8, 42.9, 61.2, 57.2, 69.8, 62.7, 51.0, 44.1, 31.7, 57.0, 71.0, 51.8, 26.1, 41.8, 54.0, 48.3, 69.2, 48.1, 33.8, 55.8, 67.7, 69.2, 53.0, 44.2, 30.2, 43.7, 69.3, 47.0, 46.1, 9.9, 38.1, 50.5, 67.1, 39.6, 49.9, 26.5, 33.0, 55.3, 44.9, 32.5, 31.4, 21.7, 41.8, 16.2, 32.6, 31.6, 55.9, 64.5, 56.0, 28.7, 51.2, 69.9, 40.9, 42.0, 47.1, 36.1, 56.2, 53.5, 66.3, 70.3, 35.6, 31.1, 32.3, 67.0, 31.3, 36.7, 50.4, 22.1, 47.1, 31.3, 2.5, 23.6, 55.8, 54.9, 57.1, 50.1, 60.6, 62.1, 48.4, 31.8, 54.1, 37.5, 37.5, 35.5, 64.7, 58.8, 42.6, 31.6, 59.9, 39.7, 32.2, 49.9, 40.6, 19.8, 33.2, 22.5, 59.7, 71.4, 47.7, 67.6, 59.6, 28.9, 55.4, 70.9, 61.8, 38.2, 46.1, 33.6, 73.6, 37.7, 33.1, 53.6, 62.8, 65.3, 66.4, 19.0, 77.8, 61.8, 34.9, 38.0, 30.0, 22.5, 51.1, 68.5, 51.0, 41.8, 40.2, 54.9, 66.6, 34.0, 25.2, 35.3, 62.9, 61.5, 64.1, 18.9, 26.2, 51.9, 3.5, 30.8, 61.5, 46.9, 46.5, 35.8, 70.6, 55.4, 43.2, 65.5, 31.6, 19.3, 21.4, 58.8, 46.8, 65.1, 65.4, 55.6, 73.5, 55.5, 63.4, 33.9, 57.5, 46.9, 50.1, 32.1, 34.8, 47.6, 38.0, 41.8, 54.7, 1.7, 65.0, 58.0, 69.2, 33.9, 35.2, 51.8, 68.9, 37.8, 28.3, 66.6, 42.4, 63.0, 44.5, 33.5, 25.4, 51.7, 33.4, 36.0, 65.0, 58.9, 70.8, 65.2, 52.7, 71.9, 59.4, 11.8, 70.0, 72.8, 63.1, 6.6, 30.6, 61.6, 63.8, 19.9, 46.7, 7.3, 53.5, 40.5, 59.1, 59.7, 57.0, 0.0, 59.6, 48.3, 59.0, 4.4, 39.5, 75.8, 46.6, 50.4, 25.3, 68.2, 40.4, 85.3, 7.0, 72.6, 42.3, 51.4, 57.8, 17.5, 36.4, 42.1, 4.4, 54.8, 64.3, 26.2, 52.0, 17.6, 38.3, 44.7, 37.3, 34.7, 28.1, 29.0, 33.6, 41.5, 59.8, 23.7, 73.2, 70.9, 72.2, 49.4, 31.6, 67.4, 46.6, 91.1, 64.0, 49.3, 41.5, 1.8, 41.1, 38.7, 34.1, 69.2, 12.5, 25.3, 32.3, 42.6, 38.7, 16.3, 56.2, 28.8, 56.8, 50.8, 59.2, 11.8, 24.3, 42.6, 52.0, 53.1, 28.9, 23.1, 65.1, 53.5, 26.2, 68.7, 60.4, 69.9, 32.4, 44.9, 61.7, 33.5, 39.1, 43.5, 22.5, 61.2, 19.6, 29.8, 32.8, 0.4, 19.5, 34.2, 69.1, 34.5, 49.6, 68.4, 61.4, 15.2, 49.3, 53.3, 23.0, 58.4, 68.2, 47.1, 34.8, 34.4, 53.5, 30.2, 58.1, 26.1, 1.2, 46.3, 32.3, 22.3, 27.6, 64.0, 59.3, 67.9, 30.9, 47.3, 59.9, 29.7, 70.1, 73.4, 34.4, 31.1, 63.2, 65.8, 51.8, 38.1, 37.0, 29.5, 49.0, 35.9, 42.9, 5.4, 41.1, 20.6, 35.9, 39.4, 62.7, 39.9, 35.2, 70.4, 54.0, 42.2, 15.5, 43.4, 28.7, 52.6, 1.3, 60.7, 69.9, 41.1, 35.4, 60.4, 30.7, 59.0, 4.6, 43.4, 37.1, 59.0, 68.2, 63.5, 10.7, 64.4, 45.1, 29.8, 24.2, 45.1, 36.5, 59.0, 44.6, 43.7, 46.0, 73.9, 52.2, 26.0, 31.7, 61.1, 51.6, 39.6, 37.8, 23.7, 64.9, 69.2, 85.2, 29.8, 47.5, 47.6, 46.0, 51.0, 34.9, 39.8, 54.2, 46.3, 67.3, 28.4, 68.8, 73.0, 47.6, 10.7, 49.2, 65.4, 45.5, 51.0, 45.4, 66.6, 21.8, 60.5, 36.8, 57.0, 51.4, 67.0, 0.9, 37.3, 67.3, 31.2, 49.8, 37.6, 47.7, 46.1, 2.6, 34.3, 48.7, 38.2, 51.3, 47.7, 49.4, 55.9, 41.5, 30.5, 40.3, 67.1, 68.6, 24.4, 21.0, 45.0, 32.3, 66.5, 67.7, 57.3, 46.6, 40.8, 41.8, 43.5, 39.3, 68.5, 53.8, 33.0, 47.3, 67.4, 17.3, 48.9, 36.5, 53.2, 56.2, 35.0, 48.9, 34.3, 62.8, 35.3, 60.3, 33.7, 24.0, 54.5, 33.7, 67.7, 32.4, 46.8, 67.0, 30.0, 10.0, 40.4, 60.5, 41.5, 75.6, 22.9, 50.2, 23.8, 66.9, 60.4, 32.5, 55.7, 19.5, 34.7, 67.2, 51.1, 42.4, 64.0, 79.4, 3.7, 49.4, 51.7, 77.3, 48.6, 34.7, 54.4, 33.3, 66.2, 41.4, 27.9, 37.9, 56.3, 24.1, 27.9, 62.8, 53.6, 55.6, 68.6, 35.2, 36.2, 32.6, 77.0, 43.8, 40.4, 60.8, 46.8, 50.6, 58.5, 4.7, 64.0, 32.8, 54.3, 46.0, 77.2, 44.4, 32.8, 43.8, 62.1, 59.1, 57.5, 7.5, 72.0, 76.9, 50.9, 69.5, 44.6, 4.1, 34.2, 29.3, 46.5, 54.1, 33.3, 57.5, 63.1, 67.9, 48.1, 29.6, 44.3, 66.8, 47.5, 75.9, 24.6, 43.2, 7.5, 55.0, 21.0, 41.4, 9.1, 49.0, 58.7, 58.7, 42.2, 59.5, 32.0, 54.1, 58.6, 25.3, 23.1, 54.7, 69.7, 32.2, 36.4, 67.2, 45.1, 42.7, 60.2, 64.1, 36.2, 77.3, 19.3, 63.0, 31.5, 70.9, 35.9, 45.2, 50.6, 51.4, 35.0, 37.9, 53.7, 28.6, 42.1, 41.9, 1.2, 54.3, 73.5, 46.6, 63.7, 38.8, 39.0, 35.5, 61.8, 61.3, 30.6, 49.9, 50.9, 55.7, 60.9, 24.9, 69.3, 62.3, 54.1, 31.1, 33.6, 61.1, 35.8, 73.1, 36.4, 34.0, 38.9, 45.8, 26.5, 34.9, 41.2, 28.0, 46.1, 59.9, 61.6, 27.6, 30.3, 67.3, 33.4, 55.5, 24.9, 64.0, 46.0, 31.4, 61.0, 69.3, 43.0, 42.9, 65.8, 64.6, 36.4, 45.8, 38.9, 57.5, 52.6, 31.5, 38.7, 70.4, 38.8, 87.5, 78.2, 46.8, 55.0, 40.5, 65.1, 31.4, 46.0, 64.8, 29.4, 2.3, 55.8, 7.5, 43.2, 54.0, 63.3, 31.7, 52.8, 39.7, 25.7, 33.5, 5.6, 9.0, 77.5, 41.1, 37.8, 32.7, 69.0, 42.9, 28.6, 29.8, 58.8, 10.9, 7.9, 50.6, 70.4, 51.8, 75.6, 50.9, 37.5, 36.8, 29.2, 10.0, 38.9, 46.1, 40.8, 54.9, 62.7, 40.8, 42.9, 58.8, 53.9, 51.4, 36.6, 46.1, 30.5, 29.1, 58.6, 23.8, 57.9, 39.8, 49.9, 27.3, 21.9, 69.0, 52.8, 28.5, 41.4, 61.8, 56.6, 51.6, 41.8, 43.2, 31.3, 62.1, 36.1, 52.4, 39.5, 58.5, 52.3, 16.8, 49.9, 71.7, 43.1, 64.4, 53.9, 30.9, 7.6, 40.1, 47.9, 68.6, 3.5, 54.4, 7.8, 45.3, 67.3, 44.6, 73.8, 49.0, 9.9, 58.8, 64.5, 21.0, 52.5, 56.9, 67.9, 37.8, 54.9, 42.3, 57.3, 22.5, 28.5, 34.0, 76.1, 63.1, 57.1, 57.5, 62.8, 70.0, 29.8, 52.4, 61.2, 50.2, 35.3, 37.5, 31.8, 26.0, 49.0, 24.0, 31.6, 56.4, 6.2, 67.1, 47.3, 40.3, 67.4, 48.9, 48.1, 21.9, 27.8, 45.1, 58.3, 33.0, 27.0, 10.2, 39.8, 60.0, 58.6, 35.1, 42.2, 55.9, 48.7, 51.7, 41.5, 59.8, 62.1, 38.3, 69.7, 31.9, 14.9, 30.3, 26.1, 14.6, 63.4, 81.7, 60.7, 64.6, 38.3, 65.1, 41.7, 17.2, 42.2, 42.8, 56.9, 47.1, 48.6, 71.5, 35.6, 52.1, 60.1, 69.0, 33.2, 54.2, 61.7, 36.8, 22.4, 71.8, 49.6, 49.8, 19.6, 36.2, 46.3, 59.6, 21.1, 64.2, 46.8, 53.7, 13.2, 42.4, 36.0, 45.4, 62.6, 29.2, 33.0, 51.4, 26.0, 60.1, 70.0, 43.8, 43.9, 37.2, 71.5, 65.7, 38.7, 47.7, 58.6, 31.9, 34.3, 29.5, 65.5, 69.2, 58.8, 82.0, 58.0, 33.4, 44.9, 27.1, 14.4, 74.0, 61.5, 48.6, 64.8, 44.1, 73.9, 6.2, 53.5, 46.4, 64.1, 22.6, 22.7, 68.1, 60.0, 39.7, 40.2, 67.4, 42.6, 64.5, 47.6, 54.7, 3.1, 24.5, 42.2, 36.1, 41.9, 45.8, 52.3, 48.6, 54.1, 24.5, 64.5, 37.2, 47.1, 33.3, 25.4, 50.9, 44.2, 63.3, 49.4, 51.4, 54.9, 48.8, 49.8, 56.5, 43.6, 46.9, 26.4, 38.1, 79.0, 6.2, 44.5, 75.4, 36.9, 72.3, 47.6, 55.4, 72.4, 70.8, 12.1, 0.5, 21.8, 1.8, 50.4, 34.1, 14.5, 42.7, 64.3, 53.9, 32.6, 26.4, 53.5, 26.7, 61.0, 61.9, 70.3, 57.5, 3.4, 32.2, 57.1, 82.6, 51.3, 45.4, 33.7, 65.3, 39.1, 66.2, 57.8, 56.8, 66.4, 69.3, 32.6, 72.9, 49.5, 44.1, 45.2, 33.0, 62.4, 67.4, 37.4, 52.8, 34.7, 12.8, 70.6, 20.0, 69.9, 64.3, 51.8, 57.7, 51.3, 56.1, 47.9, 58.5, 57.8, 49.1, 67.9, 62.2, 66.3, 49.3, 51.6, 18.8, 58.9, 58.4, 10.8, 55.1, 43.5, 36.4, 64.0, 38.0, 48.2, 67.7, 55.6, 56.3, 56.2, 51.6, 37.8, 59.0, 42.2, 24.8, 56.0, 32.0, 65.2, 56.4, 48.5, 44.8, 49.3, 28.6, 7.8, 65.6, 67.4, 69.3, 26.1, 40.8, 32.6, 66.3, 42.0, 63.0, 80.6, 51.8, 72.5, 48.9, 21.3, 56.1, 68.6, 29.8, 34.9, 72.6, 36.6, 64.7, 44.1, 40.0, 74.9, 58.1, 38.3, 27.0, 68.8, 22.5, 46.6, 72.8, 60.0, 51.0, 21.9, 45.1, 29.4, 47.5, 33.2, 46.3, 35.9, 60.1, 69.8, 46.3, 3.2, 64.1, 29.2, 71.7, 38.3, 47.0, 18.2, 40.2, 39.8, 48.9, 69.2, 39.4, 63.1, 41.3, 54.7, 72.7, 48.9, 46.0, 61.6, 42.1, 31.6, 42.0, 6.6, 39.5, 46.6, 66.3, 53.3, 27.9, 75.4, 28.0, 7.8, 77.2, 54.8, 48.5, 37.1, 34.0, 42.3, 50.5, 45.2, 65.4, 12.0, 66.7, 65.2, 53.1, 33.9, 25.8, 32.8, 9.3, 66.1, 49.5, 67.9, 65.8, 28.4, 51.4, 37.6, 16.0, 59.2, 1.4, 66.6, 37.4, 66.1, 70.9, 27.0, 56.8, 51.3, 61.6, 47.3, 44.2, 65.2, 69.9, 58.8, 7.5, 29.9, 54.9, 37.3, 57.5, 5.7, 63.4, 5.8, 32.1, 32.6, 62.1, 51.8, 69.8, 57.6, 69.3, 59.2, 49.5, 39.8, 46.0, 77.9, 40.3, 70.8, 34.7, 55.9, 22.3, 36.3, 53.7, 37.2, 41.5, 58.8, 64.8, 58.7, 67.9, 15.1, 51.6, 35.7, 69.7, 30.8, 48.0, 56.4, 30.1, 52.7, 40.5, 54.7, 62.0, 12.2, 27.3, 30.8, 23.2, 49.0, 70.1, 50.4, 32.9, 59.0, 32.8, 62.4, 60.2, 19.7, 2.4, 68.1, 52.9, 45.2, 69.3, 35.1, 58.2, 42.9, 59.9, 65.4, 68.3, 50.9, 32.3, 67.8, 37.3, 3.9, 21.1, 29.6, 65.7, 40.6, 53.7, 55.3, 26.9, 2.5, 64.0, 44.9, 57.5, 51.5, 36.8, 54.0, 44.4, 49.8, 65.2, 22.1, 30.9, 68.4, 40.1, 36.5, 63.5, 43.3, 24.3, 59.9, 9.2, 38.5, 49.5, 14.8, 47.0, 79.5, 32.1, 22.4, 57.7, 68.2, 46.7, 26.6, 22.3, 27.2, 44.2, 52.4, 59.7, 61.2, 70.7, 65.7, 60.1, 8.9, 69.8, 28.8, 68.3, 22.8, 31.9, 28.7, 18.3, 59.4, 46.4, 35.6, 42.3, 61.3, 34.9, 51.3, 42.2, 42.5, 44.0, 36.4, 24.5, 38.4, 33.4, 49.5, 3.5, 73.9, 51.5, 42.3, 53.6, 54.0, 35.9, 57.1, 41.9, 32.5, 38.3, 24.9, 42.2, 36.5, 32.5, 49.3, 60.1, 21.7, 75.1, 55.1, 52.3, 55.9, 24.6, 37.3, 60.7, 68.7, 44.3, 35.8, 52.7, 28.0, 38.4, 37.3, 36.7, 40.9, 24.8, 45.1, 56.8, 33.6, 27.2, 1.6, 70.0, 61.0, 78.1, 72.7, 49.5, 54.9, 47.6, 25.7, 53.1, 46.4, 29.9, 35.4, 69.6, 67.6, 28.2, 75.6, 44.3, 33.8, 19.1, 35.2, 44.5, 64.4, 58.4, 52.7, 76.2, 12.3, 27.4, 36.8, 68.5, 55.3, 56.4, 48.9, 52.8, 52.7, 28.8, 35.1, 65.4, 68.7, 57.7, 37.7, 11.0, 34.0, 27.7, 55.4, 15.5, 45.6, 33.9, 40.8, 72.8, 60.4, 85.2, 24.0, 64.8, 25.3, 36.5, 72.6, 13.5, 53.1, 61.4, 32.5, 52.3, 63.4, 58.7, 52.6, 50.7, 38.3, 36.9, 55.4, 3.9, 61.2, 51.2, 60.3, 28.6, 51.8, 24.4, 39.4, 44.2, 51.6, 47.0, 59.9, 39.4, 57.8, 20.1, 37.7, 25.1, 60.8, 25.5, 45.9, 57.5, 27.6, 55.6, 27.5, 37.0, 37.0, 32.8, 49.8, 46.1, 49.2, 61.8, 9.9, 29.7, 55.6, 53.6, 69.7, 39.7, 48.5, 61.9, 39.1, 49.6, 7.7, 70.3, 72.6, 58.2, 31.8, 28.4, 68.5, 62.5, 26.2, 50.4, 46.0, 62.3, 52.5, 48.0, 38.7, 53.5, 22.5, 72.6, 21.9, 24.9, 55.3, 42.4, 64.7, 60.2, 67.2, 21.6, 62.7, 50.6, 3.9, 44.1, 39.5, 52.8, 26.8, 32.3, 49.9, 65.5, 35.9, 56.1, 48.1, 29.5, 60.4, 92.6, 55.9, 69.7, 29.0, 38.4, 42.6, 20.4, 65.5, 40.6, 65.4, 66.3, 47.7, 39.7, 61.5, 60.4, 2.5, 61.3, 41.5, 43.4, 30.0, 34.4, 60.1, 36.9, 32.8, 58.5, 20.2, 62.1, 3.3, 70.6, 19.3, 50.1, 10.2, 41.8, 52.3, 19.5, 74.4, 32.6, 55.8, 23.1, 70.8, 52.0, 33.4, 2.6, 46.2, 58.4, 55.9, 58.7, 56.8, 6.8, 57.4, 50.2, 35.9, 7.7, 36.3, 39.1, 33.6, 45.8, 18.2, 28.2, 32.0, 10.7, 37.2, 64.4, 8.4, 27.4, 30.0, 65.7, 73.2, 28.5, 10.5, 58.6, 63.7, 58.1, 66.4, 37.9, 52.2, 58.7, 68.5, 27.0, 60.6, 28.9, 61.1, 55.9, 27.9, 30.1, 60.5, 50.7, 36.1, 40.4, 7.2, 63.1, 68.5, 66.1, 48.1, 40.1, 65.4, 20.1, 33.9, 60.1, 36.8, 45.9, 23.1, 47.9, 58.3, 58.2, 64.0, 60.6, 36.6, 53.4, 42.3, 79.8, 35.3, 40.4, 41.9, 43.1, 57.1, 68.3, 23.8, 73.8, 59.6, 62.8, 53.8, 20.9, 51.3, 49.1, 66.4, 52.6, 58.1, 66.2, 79.8, 48.3, 61.1, 26.3, 29.4, 27.7, 22.5, 37.5, 44.6, 5.3, 61.1, 58.0, 67.8, 32.0, 66.1, 42.7, 50.4, 39.5, 35.0, 19.1, 24.1, 50.6, 71.4, 25.1, 60.9, 69.5, 46.6, 47.1, 41.4, 64.8, 66.2, 54.6, 54.6, 38.4, 60.9, 47.5, 35.4, 48.0, 60.5, 5.7, 28.9, 61.0, 14.1, 67.4, 40.4, 32.5, 29.3, 76.4, 77.3, 2.3, 31.9, 55.2, 51.9, 30.8, 11.8, 44.9, 41.5, 39.2, 51.3, 41.1, 38.0, 47.0, 46.7, 69.3, 64.2, 22.6, 34.4, 42.7, 43.2, 49.6, 29.3, 4.8, 59.6, 63.6, 51.2, 62.2, 36.3, 39.2, 55.0, 55.3, 53.6, 30.6, 36.6, 50.3, 21.3, 61.1, 36.2, 16.5, 62.4, 57.9, 68.3, 53.6, 67.3, 44.5, 51.1, 29.7, 35.9, 41.7, 45.2, 37.0, 68.6, 42.2, 67.4, 30.3, 63.5, 35.2, 37.4, 50.6, 21.9, 71.3, 40.0, 61.0, 63.7, 49.5, 59.8, 68.9, 66.1, 37.8, 70.7, 79.5, 56.5, 29.5, 38.7, 7.6, 30.4, 42.8, 48.3, 26.4, 20.6, 57.4, 40.3, 30.0, 41.3, 73.2, 69.4, 60.5, 5.4, 58.5, 39.9, 64.3, 35.6, 29.7, 7.5, 71.0, 65.1, 48.2, 55.1, 53.1, 12.0, 45.9, 34.2, 66.8, 63.8, 60.2, 38.4, 48.8, 70.6, 55.5, 13.0, 65.2, 40.3, 33.1, 59.9, 50.8, 58.4, 27.3, 39.9, 64.8, 41.5, 52.0, 45.6, 55.6, 37.0, 24.4, 42.8, 29.8, 48.6, 58.7, 29.4, 31.9, 35.3, 18.1, 34.2, 46.0, 72.9, 72.5, 69.0, 64.6, 65.2, 39.3, 18.7, 47.7, 20.4, 59.5, 53.7, 2.5, 61.8, 55.5, 71.1, 53.3, 76.1, 25.2, 30.3, 33.8, 29.1, 39.2, 88.4, 69.1, 31.0, 72.9, 86.0, 78.5, 32.6, 23.8, 67.1, 41.3, 46.0, 71.0, 64.1, 67.3, 69.6, 54.7, 41.1, 25.0, 32.2, 64.2, 51.0, 19.5, 63.0, 27.1, 48.3, 38.3, 23.7, 2.6, 22.9, 48.8, 34.8, 49.1, 44.7, 53.0, 39.9, 23.4, 57.3, 49.6, 45.2, 46.2, 69.2, 56.1, 4.9, 29.2, 52.4, 45.9, 59.5, 66.9, 69.3, 54.3, 46.8, 61.7, 51.0, 44.3, 29.7, 44.4, 23.1, 31.0, 34.0, 67.3, 25.7, 63.3, 79.2, 24.5, 42.6, 59.2, 63.7, 61.1, 25.8, 72.9, 67.3, 49.7, 35.8, 40.5, 31.7, 57.7, 28.1, 29.7, 44.7, 44.5, 27.7, 38.2, 47.4, 16.0, 30.5, 43.2, 49.6, 51.2, 22.8, 68.1, 58.9, 55.8, 36.0, 46.0, 47.3, 62.9, 45.7, 62.3, 55.8, 70.9, 32.4, 23.2, 35.2, 32.9, 7.6, 23.2, 42.1, 28.2, 61.3, 49.6, 27.1, 60.6, 24.0, 49.4, 50.6, 5.0, 24.5, 75.7, 50.6, 51.8, 43.5, 23.9, 7.5, 56.3, 40.7, 24.4, 60.9, 73.5, 32.4, 48.3, 7.1, 65.1, 38.3, 47.2, 65.5, 53.4, 61.3, 39.9, 58.8, 60.8, 42.5, 20.6, 40.7, 31.3, 55.7, 32.9, 53.4, 30.7, 65.1, 38.2, 43.1, 33.1, 32.3, 51.7, 65.3, 69.3, 47.3, 56.0, 49.2, 40.6, 62.9, 54.2, 36.4, 54.1, 1.9, 73.2, 35.2, 42.6, 70.2, 64.5, 38.2, 62.8, 57.2, 69.5, 45.9, 68.2, 64.4, 66.7, 23.0, 64.9, 48.1, 30.9, 36.8, 32.1, 55.8, 60.0, 49.1, 43.4, 74.1, 50.8, 46.3, 47.9, 47.8, 8.5, 22.7, 65.0, 44.5, 68.6, 60.7, 24.5, 67.1, 32.6, 23.0, 58.9, 65.5, 58.8, 41.7, 65.0, 28.8, 29.7, 33.0, 64.2, 50.3, 52.6, 34.7, 28.3, 53.2, 43.2, 51.3, 25.3, 58.2, 55.8, 65.8, 30.2, 27.1, 45.6, 38.0, 27.5, 56.9, 70.0, 9.7, 42.6, 41.7, 73.7, 49.2, 33.3, 6.6, 7.8, 61.5, 56.4, 26.6, 49.2, 56.0, 29.8, 18.5, 55.4, 10.7, 61.7, 57.8, 57.0, 45.8, 49.6, 42.4, 39.3, 58.5, 64.7, 71.8, 45.5, 50.8, 9.9, 62.9, 25.9, 87.7, 66.3, 46.0, 25.0, 34.7, 64.3, 4.0, 49.9, 50.4, 58.5, 36.4, 76.9, 63.7, 31.6, 57.3, 35.0, 40.4, 35.3, 68.6, 22.9, 75.5, 51.5, 53.8, 79.9, 59.2, 55.8, 67.6, 25.0, 18.5, 23.4, 38.9, 28.7, 55.7, 50.0, 54.0, 60.4, 61.9, 56.5, 64.7, 1.5, 58.8, 41.7, 34.6, 59.5, 36.3, 69.2, 59.9, 43.9, 41.6, 49.9, 13.5, 24.3, 73.9, 49.9, 47.4, 90.3, 58.0, 68.2, 31.2, 30.0, 39.4, 50.8, 25.1, 29.8, 60.6, 34.1, 48.9, 10.0, 37.0, 55.4, 44.4, 27.8, 21.9, 55.9, 59.1, 59.5, 40.2, 33.9, 63.4, 54.8, 51.9, 32.6, 31.4, 28.8, 31.5, 41.6, 47.5, 66.5, 55.3, 33.0, 42.7, 63.6, 71.6, 33.7, 45.5, 29.9, 65.3, 39.9, 50.6, 30.6, 48.6, 44.0, 73.4, 22.2, 55.3, 61.7, 77.4, 42.7, 61.3, 60.4, 65.3, 4.8, 44.4, 40.0, 29.0, 53.0, 48.8, 13.2, 29.1, 41.4, 38.7, 53.4, 65.1, 29.6, 20.2, 48.9, 32.8, 13.0, 77.5, 0.8, 45.3, 34.6, 22.0, 27.4, 76.7, 65.8, 4.9, 67.6, 43.8, 45.9, 55.1, 48.5, 46.9, 37.5, 46.3, 63.9, 49.1, 26.7, 50.2, 69.2, 18.6, 68.6, 54.7, 64.5, 55.8, 47.9, 39.9, 29.2, 33.5, 25.6, 38.7, 68.7, 61.2, 35.1, 44.7, 6.4, 33.4, 7.2, 51.1, 51.2, 19.9, 51.3, 47.4, 51.1, 68.5, 37.8, 60.9, 29.7, 38.6, 49.8, 55.0, 58.1, 69.1, 55.9, 46.2, 64.4, 57.8, 1.4, 59.4, 9.5, 7.1, 36.9, 33.4, 80.1, 26.1, 63.8, 59.1, 51.6, 68.1, 68.1, 68.6, 53.6, 56.3, 36.8, 27.4, 56.3, 69.2, 44.3, 27.7, 32.8, 42.8, 17.0, 31.2, 22.3, 38.4, 27.5, 56.7, 58.4, 32.7, 44.5, 33.9, 57.4, 33.7, 61.7, 57.3, 50.2, 35.5, 20.5, 59.8, 29.6, 37.9, 71.8, 66.3, 66.5, 48.3, 55.8, 57.3, 31.2, 20.7, 28.2, 63.2, 65.9, 58.2, 34.1, 58.7, 43.9, 65.4, 60.3, 58.8, 52.9, 48.1, 27.6, 55.9, 67.8, 10.0, 30.8, 59.2, 37.7, 45.2, 16.2, 31.9, 47.5, 66.0, 34.5, 31.9, 44.8, 69.0, 58.8, 31.4, 61.2, 52.2, 65.6, 66.2, 65.1, 59.4, 70.7, 63.7, 31.2, 29.7, 50.7, 29.1, 31.4, 40.7, 37.4, 63.1, 57.9, 66.7, 38.1, 45.4, 32.5, 74.7, 35.0, 52.3, 68.0, 37.6, 42.9, 4.2, 32.0, 41.9, 66.1, 25.4, 42.5, 46.8, 63.0, 55.2, 44.9, 29.5, 26.9, 61.2, 69.2, 33.2, 33.9, 64.7, 34.7, 28.6, 32.3, 38.7, 37.0, 62.2, 55.1, 34.5, 44.8, 61.8, 49.2, 35.7, 62.4, 6.7, 35.6, 12.0, 71.0, 26.2, 54.3, 65.5, 50.7, 30.9, 64.7, 70.2, 34.8, 54.6, 25.4, 44.7, 43.5, 61.2, 25.3, 66.8, 46.7, 28.7, 56.6, 22.1, 44.1, 53.1, 29.9, 36.2, 15.8, 41.5, 19.1, 33.3, 64.7, 50.3, 54.5, 53.1, 58.3, 44.6, 63.4, 41.0, 55.6, 65.9, 34.2, 58.6, 72.6, 39.5, 51.3, 59.7, 40.8, 55.7, 64.6, 67.4, 62.8, 57.7, 32.5, 33.5, 54.7, 19.0, 55.1, 28.2, 31.7, 26.4, 50.7, 67.3, 29.9, 58.8, 60.1, 58.0, 70.8, 54.5, 74.4, 67.8, 58.5, 0.7, 54.0, 56.7, 48.9, 63.6, 25.9, 34.4, 45.8, 27.1, 44.5, 68.6, 38.5, 35.9, 24.8, 55.2, 21.3, 38.6, 35.7, 49.1, 67.7, 71.4, 66.6, 60.9, 64.0, 36.8, 54.6, 68.6, 65.0, 21.7, 62.5, 51.2, 37.2, 21.0, 51.7, 37.5, 28.9, 37.5, 11.0, 59.4, 61.9, 76.1, 29.4, 4.5, 65.6, 63.7, 0.7, 78.7, 45.2, 46.5, 42.9, 67.1, 63.2, 25.4, 65.7, 84.9, 34.2, 70.0, 54.9, 40.2, 63.5, 62.4, 69.6, 37.0, 33.0, 66.2, 70.2, 55.6, 31.2, 59.8, 33.0, 69.3, 30.9, 28.0, 27.9, 21.7, 59.5, 55.8, 69.3, 66.6, 14.2, 35.6, 55.5, 46.5,

,country_of_birth,ibd,host_age,ibd_diagnosis_refined,acid_reflux
0,United Kingdom,I do not have this condition,74.9,not provided,not provided
1,United States,I do not have this condition,45.6,not provided,I do not have this condition
2,Canada,I do not have this condition,64.3,not provided,I do not have this condition
3,Philippines,I do not have this condition,1.7,not provided,I do not have this condition
4,Belgium,I do not have this condition,30.5,not provided,I do not have this condition
...,...,...,...,...,...
23243,United States,I do not have this condition,54.7,not provided,I do not have this condition
23244,United States,I do not have this condition,9.1,not provided,not provided
23245,Philippines,I do not have this condition,46.1,not provided,not provided
23246,Panama,I do not have this condition,37.2,not provided,I do not have this condition
23247,United States,I do not have this condition,73.1,not provided,"Diagnosed by a medical professional (doctor, p..."

In [62]:
# load pandas on PcOA embeddings
import pandas as pd
df = pd.read_csv("../data/test_set/human_test_set_v4_10317_stool_cleaned_filtered/small_human_test_set/pcoa_unifrac_128d.tsv", sep="\t", index_col=0)

df.head()

# show sample 1 embedding arrray
print(df.iloc[0].values)
df.head()

[-2.20747675e-01  1.01932855e-01  7.41596528e-02  8.75519202e-02
 -1.90833758e-02  2.47534024e-02  9.67651988e-02 -3.13807901e-02
 -1.54947870e-02 -1.81431494e-02  9.68213572e-03 -2.57824883e-02
 -9.15328796e-02  2.04690221e-02 -5.93849175e-03 -1.17177395e-02
  6.26750728e-02 -1.11077071e-02 -4.69859062e-03 -2.16770951e-02
  1.90508616e-02 -1.98003763e-02  1.37795701e-02 -1.05463970e-02
 -1.05396218e-02 -5.47750804e-03  9.24149478e-03  1.17238843e-02
 -9.26230336e-03  1.77815472e-02  4.06860740e-02  3.13511661e-02
 -1.20219263e-02 -1.19398717e-02  6.26406513e-03  1.37613832e-02
 -1.05669150e-02 -7.51584217e-03 -4.77312175e-02  4.60423873e-03
  3.75573442e-02 -4.36971293e-02  2.99854918e-02 -5.72942549e-03
  3.58053949e-02 -1.78136864e-02 -1.00838852e-02 -3.68480492e-02
 -3.48050882e-02  1.60953648e-02  2.97098428e-02  3.48991119e-03
  3.19833119e-03  6.16646673e-03  1.42088756e-02 -3.02274809e-02
 -9.08470875e-03  8.52611223e-03  1.69752685e-03  1.28922013e-03
 -2.95772677e-02  3.39190648e-02 -6.39196050e-03 -4.90847028e-03
  1.42976764e-02  1.34217016e-02  7.14327572e-03 -7.85665002e-03
 -2.37303178e-02  1.47859311e-02  2.49414989e-02 -4.05723979e-03
  2.47062929e-02 -1.77580863e-02  9.98167262e-03  2.89739677e-02
 -1.82348121e-04  3.49383256e-02 -3.02830667e-02 -6.84088201e-03
 -1.01112038e-02  5.95880543e-04 -2.81996564e-02 -1.77363227e-02
 -1.60884495e-02 -7.19981840e-03 -7.44397245e-04  1.46625064e-02
 -7.94326545e-03  3.75933352e-03 -1.75891242e-02  1.06476879e-02
  2.09509880e-02  6.32804937e-03 -7.91957987e-03  1.36845057e-02
 -1.11538441e-02 -1.67382851e-02 -4.97904332e-03 -3.64426799e-02
  1.11854020e-02 -1.78422088e-02 -9.03830177e-03  1.23671537e-02
 -5.17802702e-03  3.94866425e-03  1.83483815e-02  4.55874832e-03
 -4.40035154e-03  8.94502374e-03 -4.59795364e-03  1.08165112e-02
 -1.58287705e-02 -8.94389318e-03 -8.65705141e-03  9.02092560e-03
 -8.66612617e-03 -4.52517018e-02 -1.81341707e-02  4.18271580e-03
  1.76436075e-04  7.81698795e-03  1.43802101e-02 -2.18512492e-03
 -1.12529481e-02  2.02095527e-02  1.29617739e-03 -2.22921853e-03]

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC119,PC120,PC121,PC122,PC123,PC124,PC125,PC126,PC127,PC128
#SampleID,,,,,,,,,,,,,,,,,,,,,
10317.000068952,-0.220748,0.101933,0.074160,0.087552,-0.019083,0.024753,0.096765,-0.031381,-0.015495,-0.018143,...,-0.018134,0.004183,0.000176,0.007817,0.014380,-0.002185,-0.011253,0.020210,0.001296,-0.002229
10317.000010121,-0.073468,0.056386,0.075175,0.035734,-0.048489,-0.016126,-0.075775,0.012261,0.005084,-0.016214,...,0.012519,0.003936,-0.003869,0.003937,-0.003871,0.020602,-0.011327,0.000938,-0.023318,-0.012972
10317.000074841,0.317487,0.052352,0.179231,0.064255,0.048005,0.009229,-0.031858,0.092285,0.041188,-0.048499,...,0.034030,0.021550,-0.014371,0.018587,-0.002063,-0.000050,-0.000950,0.012535,0.034088,-0.034518
10317.000116304,-0.044913,-0.194850,-0.055408,-0.099490,0.059005,-0.028117,0.020583,-0.004798,0.022232,-0.018132,...,0.012976,-0.001030,0.000318,0.009470,0.007801,-0.019035,-0.002901,0.042147,0.023617,0.022861
10317.000066998,0.175066,0.026144,-0.000806,-0.073150,-0.033313,-0.053787,-0.035493,-0.071881,0.030153,0.039513,...,-0.003180,-0.006272,0.014779,0.003074,0.008558,0.002440,-0.003548,0.009268,0.015277,0.031801

In [ ]:
import pandas as pd
from skbio import DistanceMatrix
from skbio.stats.ordination import pcoa
import matplotlib.pyplot as plt

# 1. Load UniFrac
dm_df = pd.read_csv("unifrac.tsv", sep="\t", index_col=0)
dm = DistanceMatrix(dm_df.values, ids=dm_df.index)

# 2. PCoA
pcoa_results = pcoa(dm)
coords = pcoa_results.samples  # rows = samples

# 3. Load metadata and add study_id if needed
meta = pd.read_csv("metadata.tsv", sep="\t").set_index("sample-id")

if "study_id" not in meta.columns:
    meta["study_id"] = meta.index.str.split(".").str[0]

coords = coords.join(meta, how="inner")

# 4. Plot: color by study_id, shape by geo_loc_name
plt.figure(figsize=(7, 6))

markers = {name: marker for name, marker in zip(
    coords["geo_loc_name"].unique(),
    ['o', 's', '^', 'D', 'P', 'X', '*']
)}

for (geo_loc), group in coords.groupby("geo_loc_name"):
    marker = markers.get(geo_loc, 'o')
    sc = plt.scatter(
        group["PC1"],
        group["PC2"],
        marker=marker,
        alpha=0.7,
        c=pd.Categorical(group["study_id"]).codes,
    )

plt.xlabel(f"PC1 ({pcoa_results.proportion_explained['PC1']*100:.1f}% var)")
plt.ylabel(f"PC2 ({pcoa_results.proportion_explained['PC2']*100:.1f}% var)")
plt.title("PCoA on UniFrac – color=study_id, shape=geo_loc_name")
plt.tight_layout()
plt.show()